export interface TeamMember {
  fname: string;
  lname: string;
  nickname: string;
  university: string;
  program: string;
  year: string;
  image: string;
  university_image: string;
  pronouns: string;
  roles: string[];
  sub_role: string;
  linkedin: string;
  instagram: string;
  github: string;
  website: string;
  email: string;
}

const teamMembers: TeamMember[] = [
  {
    fname: "Timothy",
    lname: "Klint",
    nickname: "TJ",
    university: "John Abbott College",
    program: "Computer Science",
    year: "3rd Year",
    image: "",
    university_image: "",
    pronouns: "He/Him",
    roles: ["Co-Chair"],
    sub_role: "",
    linkedin: "https://www.linkedin.com/in/timothy-klint/",
    instagram: "https://www.instagram.com/tj_klint/",
    github: "https://github.com/tjklint",
    website: "https://tjklint.github.io/",
    email: "timothyjklint@gmail.com",
  },
  {
    fname: "Kha",
    lname: "Pham",
    nickname: "Kha",
    university: "University of Manitoba",
    program: "Computer Science",
    year: "Graduated",
    image: "",
    university_image: "",
    pronouns: "He/Him",
    roles: ["Co-Chair"],
    sub_role: "",
    linkedin: "https://www.linkedin.com/in/khathepham/",
    instagram: "https://www.instagram.com/khathepham.photos/",
    github: "https://github.com/khathepham",
    website: "Khathepham.com",
    email: "contact@khathepham.com",
  },
  {
    fname: "Jaelyn",
    lname: "Wickramarachchi",
    nickname: "",
    university: "University Of Manitoba",
    program: "Economics with Computer Science",
    year: "4th Year",
    image: "",
    university_image: "",
    pronouns: "She/Her",
    roles: ["Director of Logistics"],
    sub_role: "",
    linkedin: "",
    instagram: "https://www.instagram.com/jae.wickk/",
    github: "",
    website: "",
    email: "",
  },
  {
    fname: "Michael",
    lname: "Xie",
    nickname: "",
    university: "University of Waterloo",
    program: "Computer Science",
    year: "3rd Year",
    image: "",
    university_image: "",
    pronouns: "",
    roles: ["Logistics Team"],
    sub_role: "",
    linkedin: "https://www.linkedin.com/in/michael-xie1/",
    instagram: "",
    github: "https://github.com/derzz",
    website: "https://www.michaelxie.ca/",
    email: "",
  },
  {
    fname: "Angeleeca",
    lname: "Jocson",
    nickname: "Angie",
    university: "University of Ottawa",
    program: "omputer Science and Mathematics",
    year: "4th Year",
    image: "",
    university_image: "",
    pronouns: "She/Her",
    roles: ["Director of Sponsorship"],
    sub_role: "",
    linkedin: "https://www.linkedin.com/in/angeleeca-jocson/",
    instagram: "https://www.instagram.com/altth3a/",
    github: "",
    website: "",
    email: "angeleeca.jocson@gmail.com",
  },
  {
    fname: "Arfah",
    lname: "Huda",
    nickname: "",
    university: "University of Windsor",
    program: "Computer Science and Mathematics",
    year: "4th Year",
    image: "",
    university_image: "",
    pronouns: "",
    roles: ["Sponsorship Team"],
    sub_role: "",
    linkedin: "https://www.linkedin.com/in/arfahhuda/",
    instagram: "https://www.instagram.com/arfahhuda/",
    github: "",
    website: "",
    email: "",
  },
  {
    fname: "Tara",
    lname: "Denaud Joseph",
    nickname: "",
    university: "University of Ottawa ",
    program: "Honours BSc Computer Science",
    year: "3rd Year",
    image: "",
    university_image: "",
    pronouns: "",
    roles: ["Director of Speakers"],
    sub_role: "",
    linkedin: "www.linkedin.com/in/taradenaud",
    instagram: "https://www.instagram.com/taradenaud/",
    github: "https://github.com/taradenaud",
    website: "taradenaud.com",
    email: "taradenaud4@gmail.com",
  },
  {
    fname: "Janelle",
    lname: "Tam",
    nickname: "",
    university: "McGill University",
    program: "Software Engineering",
    year: "2nd Year",
    image: "",
    university_image: "",
    pronouns: "",
    roles: ["Speakers Team"],
    sub_role: "",
    linkedin: "https://www.linkedin.com/in/janellewstam/",
    instagram: "https://www.instagram.com/_janelletam_",
    github: "https://github.com/janelletam",
    website: "",
    email: "janelletam.work@gmail.com",
  },
  {
    fname: "Tyrell",
    lname: "Haywood",
    nickname: "",
    university: "Carleton University",
    program: "Computer Science",
    year: "2nd Year",
    image: "",
    university_image: "",
    pronouns: "He/Him",
    roles: ["Director of Technology"],
    sub_role: "",
    linkedin: "https://www.linkedin.com/in/tyrell-haywood/",
    instagram: "https://www.instagram.com/tyrell.haywood/",
    github: "https://github.com/TyrellHaywood",
    website: "https://www.tyrellhaywood.me/",
    email: "tyrellchaywood@gmail.com",
  },
  {
    fname: "Taryn",
    lname: "Beaupre",
    nickname: "",
    university: "John Abbott College",
    program: "Computer Science",
    year: "",
    image: "",
    university_image: "",
    pronouns: "She/Her",
    roles: ["Director of Promotions", "Tech UI/UX Designer"],
    sub_role: "",
    linkedin: "https://www.linkedin.com/in/taryn-beaupre/",
    instagram: "https://www.instagram.com/taryn.beaupre/",
    github: "https://github.com/TarynBeaupre",
    website: "",
    email: "",
  },
  {
    fname: "",
    lname: "",
    nickname: "",
    university: "",
    program: "",
    year: "",
    image: "",
    university_image: "",
    pronouns: "",
    roles: [""],
    sub_role: "",
    linkedin: "",
    instagram: "",
    github: "",
    website: "",
    email: "",
  },
  {
    fname: "",
    lname: "",
    nickname: "",
    university: "",
    program: "",
    year: "",
    image: "",
    university_image: "",
    pronouns: "",
    roles: [""],
    sub_role: "",
    linkedin: "",
    instagram: "",
    github: "",
    website: "",
    email: "",
  },
  {
    fname: "",
    lname: "",
    nickname: "",
    university: "",
    program: "",
    year: "",
    image: "",
    university_image: "",
    pronouns: "",
    roles: [""],
    sub_role: "",
    linkedin: "",
    instagram: "",
    github: "",
    website: "",
    email: "",
  },
  {
    fname: "",
    lname: "",
    nickname: "",
    university: "",
    program: "",
    year: "",
    image: "",
    university_image: "",
    pronouns: "",
    roles: [""],
    sub_role: "",
    linkedin: "",
    instagram: "",
    github: "",
    website: "",
    email: "",
  },
  {
    fname: "",
    lname: "",
    nickname: "",
    university: "",
    program: "",
    year: "",
    image: "",
    university_image: "",
    pronouns: "",
    roles: [""],
    sub_role: "",
    linkedin: "",
    instagram: "",
    github: "",
    website: "",
    email: "",
  },
];

export default teamMembers;
